apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-parsers
data:
  parsers.conf: |
    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep   On
